version: "3.5"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: $APPNAME
    restart: unless-stopped
    user: 'root'
    labels:
        traefik.backend: $APPNAME
        traefik.docker.network: "web"
        traefik.enable: "true"
        traefik.frontend.passHostHeader: "true"
        traefik.frontend.rule: "PathPrefixStrip:/$APPNAME"
        traefik.port: "8050" # update to Exposed port from Dockerfile
        traefik.http.middlewares.test-auth.basicauth.users: "test:bestpassword"
    ports:
      - 1769:8050 #update both ports (1769 is project port (must be unique!), 8050 is Exposed from Dockerfile (can be duplicate!))
    networks:
      - web

networks:
  web:
    external:
      name: web

